name: Build and deploy docs

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "30 4 * * *" # Every day at 4:30 UTC

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Lix
        uses: samueldr/lix-gha-installer-action@7b7f14d320d6aacfb65bd1ef761566b3b69e474c # v2026-02-22

      - name: Build Docs
        run: nix build

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "result/"

  deploy:
    needs: build
    runs-on: "ubuntu-latest"

    permissions:
      pages: "write"
      id-token: "write"

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
